// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT1m2w0n4xVy-nbWFb59HeNKN4YeWDsk8',
    appId: '1:351774807398:web:b6c591359d0513bae3a4a7',
    messagingSenderId: '351774807398',
    projectId: 'social-wall-bbc71',
    authDomain: 'social-wall-bbc71.firebaseapp.com',
    storageBucket: 'social-wall-bbc71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlj_6-ISZ1FDhRd-kVHWCOIzL2A5zhpdM',
    appId: '1:351774807398:android:6a9b7a9fa485e239e3a4a7',
    messagingSenderId: '351774807398',
    projectId: 'social-wall-bbc71',
    storageBucket: 'social-wall-bbc71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALdpVajGA_NG3N2AfqFYFiGAhZfaw7oYQ',
    appId: '1:351774807398:ios:43b03ba938c34fcfe3a4a7',
    messagingSenderId: '351774807398',
    projectId: 'social-wall-bbc71',
    storageBucket: 'social-wall-bbc71.appspot.com',
    iosBundleId: 'com.example.socialWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALdpVajGA_NG3N2AfqFYFiGAhZfaw7oYQ',
    appId: '1:351774807398:ios:43b03ba938c34fcfe3a4a7',
    messagingSenderId: '351774807398',
    projectId: 'social-wall-bbc71',
    storageBucket: 'social-wall-bbc71.appspot.com',
    iosBundleId: 'com.example.socialWall',
  );
}
